### ISSUE TITLE
Unclear button meaning

### ISSUE THREAD

**Issue by EthanJStark** [GuildCrafts/prrr#130]
As a user reviewing a PRRR, it is not immediately clear what the results of clicking "Skip" or "Abandon" will be. Specifically, if I press either of these buttons, will I ever be able to claim the PRRR again?

This might be solved with text appearing on mouse-over of the buttons.

**Comment by deadlyicon** [comment]
What would be more clear?

**Comment by EthanJStark** [comment]
Well, first off, I'd need to know what the buttons do. If I skip, will that Prrr eventually come back up for me if I keep claiming? Will it come up immediately? Will I get another Prrr right away? I don't know these things 'cause I usually just review 'em.
Abandon, I assume, means that I'll never see it again, yes?

**Comment by deadlyicon** [comment]
okay I am convinced the names are confusing. unless you can suggest some better names I'm going to do nothing since these features are going away soon

**Comment by EthanJStark** [comment]
Oh sure, that's fine. Thanks.
