### ISSUE TITLE
As a user claiming a request, I would like to see a deadline to complete the review. 

### ISSUE THREAD

**Issue by pllearns** [GuildCrafts/prrr#3]

**Comment by deadlyicon** [comment]
I was thinking of adding a second step. First you `claim` then you `complete` the review. And your open reviews are at the top with a timer for how long they're been claimed but incomplete for. Maybe the timer goes red after an hour?

maybe stale reviews can be stolen?

**Comment by deadlyicon** [comment]
@shereefb thoughts?

**Comment by shereefb** [comment]
For now just an expectation that it should be done in an hour.

**Comment by deadlyicon** [comment]
I'm closing this in favor of https://github.com/GuildCrafts/prrr/issues/5
