### ISSUE TITLE
Unclaiming and claiming returns different Prrr

### ISSUE THREAD

**Issue by deonna** [GuildCrafts/prrr#56]
0. you see "there are 12 PRs pending review, click here to claim one"
1. you click that button
2. you decide your review is not useful enough
3. you unclaim
4. you click claim again (and you get a different Prrr)

[This.](https://github.com/GuildCrafts/prrr/issues/33#issuecomment-272517772)

**Comment by shereefb** [comment]
@deadlyicon +1 for me on this one as well. 
Planning on using prrr for project reviews at the end of the cycle and this is critical to make it work. Otherwise, if I pick a review that's too advanced for me, I can't find the next one.
