### ISSUE TITLE
Some Prrrs can be added but not claimed?

### ISSUE THREAD

**Issue by deonna** [GuildCrafts/prrr#68]
![prrr](https://cloud.githubusercontent.com/assets/20684747/22037815/a93f5306-dcad-11e6-9145-a0dec0ff517c.jpg)

**Comment by deadlyicon** [comment]
thanks! :)

**Comment by deadlyicon** [comment]
FYI this is a limitation where the owner of the repo needs to have a Prrr account so we can use their API key to add the claimer as a collaborator. We still need to discover a solution around this but ATM its a significant limitation
